const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Function,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Behaviors.Car,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.destroy,
		C3.Plugins.shadowlight,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Car.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Car.Acts.SetSpeed,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Car.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Car.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Pathfinding.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Behaviors.Car.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Behaviors.Car.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Mouse.Cnds.OnAnyClick
	];
};
self.C3_JsPropNameTable = [
	{function: 0},
	{Pin: 0},
	{laser_tank_mayhem: 0},
	{Mouse: 0},
	{gun_tank_mayhem: 0},
	{Car: 0},
	{Rotate: 0},
	{Solid: 0},
	{LineOfSight: 0},
	{LineOfSight2: 0},
	{blue_tank: 0},
	{Pathfinding: 0},
	{LineOfSight3: 0},
	{red_tank: 0},
	{bonus_armor_4_tank_mayhem: 0},
	{bonus_trible_1_tank_mayhem: 0},
	{bonus_missile_7_tank_mayhem: 0},
	{bonus_ghost_tank_mayhem: 0},
	{bonus_patlayn_mermi_5_tank_mayhem: 0},
	{bonus_laser_2_tank_mayhem: 0},
	{Fade: 0},
	{blue_armor_tank_mayhem: 0},
	{red_armor_tank_mayhem: 0},
	{Bullet: 0},
	{duman_tank_mayhem: 0},
	{armor_no: 0},
	{big_bullet_red_tank_mayhem: 0},
	{hit: 0},
	{health: 0},
	{bullet_default_tank_mayhem: 0},
	{blue_laser_bullet_tank_mayhem: 0},
	{Default17_tank_mayhem: 0},
	{tank_particle_tank_mayhem: 0},
	{mirror2_tank_mayhem: 0},
	{simsek_tank_mayhem: 0},
	{palet_iz_tank_mayhem: 0},
	{kivilcim_tank_mayhem: 0},
	{Keyboard: 0},
	{kivilcimspavn_1_blue_tank_mayhem: 0},
	{kivilcimspavn_2_blue_tank_mayhem: 0},
	{kivilcimspavn_3_blue_tank_mayhem: 0},
	{kivilcimspavn_1_red_tank_mayhem: 0},
	{kivilcimspavn_2_red_tank_mayhem: 0},
	{kivilcimspavn_3_red_tank_mayhem: 0},
	{red_tank_part_tank_mayhem: 0},
	{blue_tank_part_tank_mayhem: 0},
	{"0006__0005_Layer0copy_tank_mayhem": 0},
	{"0005__0005_Layer0copycopy_tank_mayhem": 0},
	{blue_deafult_tank_mayhem: 0},
	{blue_big_tank_mayhem: 0},
	{blue_laser_tank_mayhem: 0},
	{red_laser_tank_mayhem: 0},
	{red_default_tank_mayhem: 0},
	{red_big_tank_mayhem: 0},
	{red_fuze_tank_mayhem: 0},
	{blue_timer: 0},
	{blue_fuze_tank_mayhem: 0},
	{"0003_Layer_tank_mayhem": 0},
	{fuze_duman_tank_mayhem: 0},
	{"0001_Layer7copy_tank_mayhem": 0},
	{gun_red_tank_mayhem: 0},
	{Flash: 0},
	{laser_red_tank_mayhem: 0},
	{blue_trible_tank_mayhem: 0},
	{red_trible_tank_mayhem: 0},
	{blue_laser_trace_tank_mayhem: 0},
	{lasercam_tank_mayhem: 0},
	{laserparticle_blue_tank_mayhem: 0},
	{lasercarpma_red_tank_mayhem: 0},
	{laserparticle_red_tank_mayhem: 0},
	{lasercarpma_blue_tank_mayhem: 0},
	{laser_duman_tank_mayhem: 0},
	{laseryasit_redtank_tank_mayhem: 0},
	{Audio: 0},
	{skorduman_tank_mayhem: 0},
	{TiledBackground_tank_mayhem: 0},
	{Tween: 0},
	{"0009_Layer_tank_mayhem": 0},
	{"1P": 0},
	{"2P": 0},
	{ScrollTo: 0},
	{camera: 0},
	{mermisekmeduman_tank_mayhem: 0},
	{TiledBackground4_tank_mayhem: 0},
	{solid_out_line_tank_mayhem: 0},
	{ShadowCaster: 0},
	{DestroyOutsideLayout: 0},
	{duvarlar: 0},
	{DragDrop: 0},
	{ShadowLightblue: 0},
	{ShadowLightred: 0},
	{bonus_dron_tank_6_tank_mayhem: 0},
	{bonus_duvar_delen_3_tank_mayhem: 0},
	{bluedron_tank_mayhem: 0},
	{reddron_tank_mayhem: 0},
	{Touch: 0},
	{dark_tank_mayhem: 0},
	{homee_tank_mayhem_anchor: 0},
	{light_tank_mayhem_anchor: 0},
	{pause_tank_mayhem: 0},
	{bullet_default2_tank_mayhem: 0},
	{bludronbullet_tank_mayhem: 0},
	{reddronbullet_tank_mayhem: 0},
	{dronpalet_izi_tank_mayhem: 0},
	{bludronatesefekt_tank_mayhem: 0},
	{reddronatesefekt_tank_mayhem: 0},
	{reddronsignall_tank_mayhem: 0},
	{rbluedronsignal_tank_mayhem: 0},
	{duvardelenblue_tank_mayhem: 0},
	{duvardelenred_tank_mayhem: 0},
	{big_bullet_blue_tank_mayhem: 0},
	{missile: 0},
	{blue_fuze_go_tank_mayhem: 0},
	{red_fuze_go_tank_mayhem: 0},
	{booomm: 0},
	{fuzeboomleke_tank_mayhem: 0},
	{bonusmode: 0},
	{bonus_spawnerr_tank_mayhem: 0},
	{endscrleftbtn_tank_mayhem: 0},
	{endscrrightbtn_tank_mayhem: 0},
	{mainmenu_tank_mayhem: 0},
	{playagain_tank_mayhem: 0},
	{sound_tank_mayhem: 0},
	{solid_out_line2_tank_mayhem: 0},
	{blue_bullet_tank_mayhem: 0},
	{red_bullet_tank_mayhem: 0},
	{enter_tank_mayhem: 0},
	{exit_tank_mayhem: 0},
	{"1pradar_tank_mayhem": 0},
	{Text_tank_mayhem: 0},
	{laser_kilavuz_tank_mayhem: 0},
	{gerisay_tank_mayhem: 0},
	{Red_Scoreboard_anchor: 0},
	{Blue_Scoreboard_anchor: 0},
	{Game_Name: 0},
	{End_Score: 0},
	{End_Score2: 0},
	{Anchor: 0},
	{blue_Score_anchor: 0},
	{red_Score_anchor: 0},
	{Tank: 0},
	{Wins: 0},
	{TiledBackground_tank_mayhem2: 0},
	{duvarkose: 0},
	{yan: 0},
	{alt: 0},
	{Browser: 0},
	{Sprite4: 0},
	{ai_bullet: 0},
	{howtpblue: 0},
	{howtpred: 0},
	{joybg: 0},
	{joy: 0},
	{line: 0},
	{joybg2: 0},
	{joy2: 0},
	{line2: 0},
	{shoot2: 0},
	{shoot: 0},
	{bonus_tank_mayhem: 0},
	{namlular_tank_mayhem: 0},
	{wall__red_tank_mayhem: 0},
	{wall__blue_tank_mayhem: 0},
	{red_tank_family_tank_mayhem: 0},
	{Blue_tank_family_tank_mayhem: 0},
	{tweeen_tank_mayhem: 0},
	{buttton_tank_mayhem: 0},
	{bullet_tank_mayhem: 0},
	{effectgray_tank_mayhem: 0},
	{idealbonus_tank_mayhem: 0},
	{reversee_tank_mayhem: 0},
	{efektler_tank_mayhem: 0},
	{adbutton_tank_mayhem: 0},
	{sagsol: 0},
	{anchorr: 0},
	{Family1: 0},
	{all_texts: 0},
	{hwtplay: 0},
	{start: 0},
	{"0tankagit1bonusaagit": 0},
	{blue_atis_hakki: 0},
	{red_atis_hakki: 0},
	{"1P_OR_2P": 0},
	{maze_angle: 0},
	{volume: 0},
	{red_or_blue: 0},
	{bonus_spawner: 0},
	{duvardelenaktif_red: 0},
	{duvardelenaktif_blue: 0},
	{bonus_alim_blue: 0},
	{bonus_alim_red: 0},
	{red_tank_moved: 0},
	{blue_tank_moved: 0},
	{red_default_atis: 0},
	{blue_default_atis: 0},
	{lights: 0},
	{temacolor: 0},
	{blue_skor: 0},
	{red_skor: 0},
	{blue_laser_height: 0},
	{red_laser: 0},
	{blue_laser: 0},
	{ang: 0},
	{x: 0},
	{y: 0},
	{scale_zoom: 0},
	{Mobil_Pc: 0},
	{epsilon: 0},
	{nx: 0},
	{ny: 0},
	{bestT: 0},
	{x1: 0},
	{x2: 0},
	{y1: 0},
	{y2: 0},
	{x3: 0},
	{y3: 0},
	{x4: 0},
	{y4: 0},
	{denom: 0},
	{t: 0},
	{s: 0},
	{zoomOk: 0},
	{distanceAllowed: 0},
	{end_scr: 0},
	{ses: 0},
	{Main_Sound: 0}
];

self.InstanceType = {
	function: class extends self.IInstance {},
	laser_tank_mayhem: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	gun_tank_mayhem: class extends self.ISpriteInstance {},
	blue_tank: class extends self.ISpriteInstance {},
	red_tank: class extends self.ISpriteInstance {},
	bonus_armor_4_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_trible_1_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_missile_7_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_ghost_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_patlayn_mermi_5_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_laser_2_tank_mayhem: class extends self.ISpriteInstance {},
	blue_armor_tank_mayhem: class extends self.ISpriteInstance {},
	red_armor_tank_mayhem: class extends self.ISpriteInstance {},
	duman_tank_mayhem: class extends self.ISpriteInstance {},
	big_bullet_red_tank_mayhem: class extends self.ISpriteInstance {},
	bullet_default_tank_mayhem: class extends self.ISpriteInstance {},
	blue_laser_bullet_tank_mayhem: class extends self.ISpriteInstance {},
	Default17_tank_mayhem: class extends self.ISpriteInstance {},
	tank_particle_tank_mayhem: class extends self.ISpriteInstance {},
	mirror2_tank_mayhem: class extends self.ISpriteInstance {},
	simsek_tank_mayhem: class extends self.ISpriteInstance {},
	palet_iz_tank_mayhem: class extends self.ISpriteInstance {},
	kivilcim_tank_mayhem: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	kivilcimspavn_1_blue_tank_mayhem: class extends self.ISpriteInstance {},
	kivilcimspavn_2_blue_tank_mayhem: class extends self.ISpriteInstance {},
	kivilcimspavn_3_blue_tank_mayhem: class extends self.ISpriteInstance {},
	kivilcimspavn_1_red_tank_mayhem: class extends self.ISpriteInstance {},
	kivilcimspavn_2_red_tank_mayhem: class extends self.ISpriteInstance {},
	kivilcimspavn_3_red_tank_mayhem: class extends self.ISpriteInstance {},
	red_tank_part_tank_mayhem: class extends self.ISpriteInstance {},
	blue_tank_part_tank_mayhem: class extends self.ISpriteInstance {},
	_0006__0005_Layer0copy_tank_mayhem: class extends self.ISpriteInstance {},
	_0005__0005_Layer0copycopy_tank_mayhem: class extends self.ISpriteInstance {},
	blue_deafult_tank_mayhem: class extends self.ISpriteInstance {},
	blue_big_tank_mayhem: class extends self.ISpriteInstance {},
	blue_laser_tank_mayhem: class extends self.ISpriteInstance {},
	red_laser_tank_mayhem: class extends self.ISpriteInstance {},
	red_default_tank_mayhem: class extends self.ISpriteInstance {},
	red_big_tank_mayhem: class extends self.ISpriteInstance {},
	red_fuze_tank_mayhem: class extends self.ISpriteInstance {},
	blue_fuze_tank_mayhem: class extends self.ISpriteInstance {},
	_0003_Layer_tank_mayhem: class extends self.ISpriteInstance {},
	fuze_duman_tank_mayhem: class extends self.ISpriteInstance {},
	_0001_Layer7copy_tank_mayhem: class extends self.ISpriteInstance {},
	gun_red_tank_mayhem: class extends self.ISpriteInstance {},
	laser_red_tank_mayhem: class extends self.ISpriteInstance {},
	blue_trible_tank_mayhem: class extends self.ISpriteInstance {},
	red_trible_tank_mayhem: class extends self.ISpriteInstance {},
	blue_laser_trace_tank_mayhem: class extends self.ISpriteInstance {},
	lasercam_tank_mayhem: class extends self.ISpriteInstance {},
	laserparticle_blue_tank_mayhem: class extends self.ISpriteInstance {},
	lasercarpma_red_tank_mayhem: class extends self.ISpriteInstance {},
	laserparticle_red_tank_mayhem: class extends self.ISpriteInstance {},
	lasercarpma_blue_tank_mayhem: class extends self.ISpriteInstance {},
	laser_duman_tank_mayhem: class extends self.ISpriteInstance {},
	laseryasit_redtank_tank_mayhem: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	skorduman_tank_mayhem: class extends self.ISpriteInstance {},
	TiledBackground_tank_mayhem: class extends self.ITiledBackgroundInstance {},
	_0009_Layer_tank_mayhem: class extends self.ISpriteInstance {},
	_1P: class extends self.ISpriteInstance {},
	_2P: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	mermisekmeduman_tank_mayhem: class extends self.ISpriteInstance {},
	TiledBackground4_tank_mayhem: class extends self.ITiledBackgroundInstance {},
	solid_out_line_tank_mayhem: class extends self.ISpriteInstance {},
	duvarlar: class extends self.ISpriteInstance {},
	ShadowLightblue: class extends self.IShadowLightInstance {},
	ShadowLightred: class extends self.IShadowLightInstance {},
	bonus_dron_tank_6_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_duvar_delen_3_tank_mayhem: class extends self.ISpriteInstance {},
	bluedron_tank_mayhem: class extends self.ISpriteInstance {},
	reddron_tank_mayhem: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	dark_tank_mayhem: class extends self.ISpriteInstance {},
	homee_tank_mayhem_anchor: class extends self.ISpriteInstance {},
	light_tank_mayhem_anchor: class extends self.ISpriteInstance {},
	pause_tank_mayhem: class extends self.ISpriteInstance {},
	bullet_default2_tank_mayhem: class extends self.ISpriteInstance {},
	bludronbullet_tank_mayhem: class extends self.ISpriteInstance {},
	reddronbullet_tank_mayhem: class extends self.ISpriteInstance {},
	dronpalet_izi_tank_mayhem: class extends self.ISpriteInstance {},
	bludronatesefekt_tank_mayhem: class extends self.ISpriteInstance {},
	reddronatesefekt_tank_mayhem: class extends self.ISpriteInstance {},
	reddronsignall_tank_mayhem: class extends self.ISpriteInstance {},
	rbluedronsignal_tank_mayhem: class extends self.ISpriteInstance {},
	duvardelenblue_tank_mayhem: class extends self.ISpriteInstance {},
	duvardelenred_tank_mayhem: class extends self.ISpriteInstance {},
	big_bullet_blue_tank_mayhem: class extends self.ISpriteInstance {},
	blue_fuze_go_tank_mayhem: class extends self.ISpriteInstance {},
	red_fuze_go_tank_mayhem: class extends self.ISpriteInstance {},
	booomm: class extends self.ISpriteInstance {},
	fuzeboomleke_tank_mayhem: class extends self.ISpriteInstance {},
	bonus_spawnerr_tank_mayhem: class extends self.ISpriteInstance {},
	endscrleftbtn_tank_mayhem: class extends self.ISpriteInstance {},
	endscrrightbtn_tank_mayhem: class extends self.ISpriteInstance {},
	mainmenu_tank_mayhem: class extends self.ISpriteInstance {},
	playagain_tank_mayhem: class extends self.ISpriteInstance {},
	sound_tank_mayhem: class extends self.ISpriteInstance {},
	solid_out_line2_tank_mayhem: class extends self.ISpriteInstance {},
	blue_bullet_tank_mayhem: class extends self.ISpriteInstance {},
	red_bullet_tank_mayhem: class extends self.ISpriteInstance {},
	enter_tank_mayhem: class extends self.ISpriteInstance {},
	exit_tank_mayhem: class extends self.ISpriteInstance {},
	_1pradar_tank_mayhem: class extends self.ISpriteInstance {},
	Text_tank_mayhem: class extends self.ITextInstance {},
	laser_kilavuz_tank_mayhem: class extends self.ISpriteInstance {},
	gerisay_tank_mayhem: class extends self.ISpriteInstance {},
	Red_Scoreboard_anchor: class extends self.ISpriteInstance {},
	Blue_Scoreboard_anchor: class extends self.ISpriteInstance {},
	Game_Name: class extends self.ITextInstance {},
	End_Score: class extends self.ITextInstance {},
	End_Score2: class extends self.ITextInstance {},
	blue_Score_anchor: class extends self.ITextInstance {},
	red_Score_anchor: class extends self.ITextInstance {},
	Tank: class extends self.ITextInstance {},
	Wins: class extends self.ITextInstance {},
	TiledBackground_tank_mayhem2: class extends self.ITiledBackgroundInstance {},
	duvarkose: class extends self.ISpriteInstance {},
	yan: class extends self.ISpriteInstance {},
	alt: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	ai_bullet: class extends self.ISpriteInstance {},
	howtpblue: class extends self.ISpriteInstance {},
	howtpred: class extends self.ISpriteInstance {},
	joybg: class extends self.ISpriteInstance {},
	joy: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	joybg2: class extends self.ISpriteInstance {},
	joy2: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	shoot2: class extends self.ISpriteInstance {},
	shoot: class extends self.ISpriteInstance {},
	bonus_tank_mayhem: class extends self.ISpriteInstance {},
	namlular_tank_mayhem: class extends self.ISpriteInstance {},
	wall__red_tank_mayhem: class extends self.ISpriteInstance {},
	wall__blue_tank_mayhem: class extends self.ISpriteInstance {},
	red_tank_family_tank_mayhem: class extends self.ISpriteInstance {},
	Blue_tank_family_tank_mayhem: class extends self.ISpriteInstance {},
	tweeen_tank_mayhem: class extends self.ISpriteInstance {},
	buttton_tank_mayhem: class extends self.ISpriteInstance {},
	bullet_tank_mayhem: class extends self.ISpriteInstance {},
	effectgray_tank_mayhem: class extends self.ISpriteInstance {},
	idealbonus_tank_mayhem: class extends self.ISpriteInstance {},
	reversee_tank_mayhem: class extends self.ISpriteInstance {},
	efektler_tank_mayhem: class extends self.ISpriteInstance {},
	adbutton_tank_mayhem: class extends self.ISpriteInstance {},
	sagsol: class extends self.ISpriteInstance {},
	anchorr: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	all_texts: class extends self.ITextInstance {}
}